### ISSUE TITLE
What does reverse option do?

### ISSUE THREAD

**Issue by arunoda** [svasva/meteor-publish-with-relations#10]
What is expected behaviour of the `reverse` option?

**Comment by jonjamz** [comment]
It has to do with where the foreign key is (the _key_ property in mappings). For example, if _b_ is the collection in mappings, and _a_ is the collection first defined in publishWithRelations:

a._id <- b.foreignKey is reverse
a.foreignKey -> b._id is not reverse

**Note: this package currently has some bugs that make it generally unusable in production. As an alternative, try storing the required data from one subscription in a reactive data type on the client side, such as a Session variable, and using Deps.autorun to re-run dependent subscriptions as that data changes.**

**Comment by arunoda** [comment]
Okay. I got it. Since this is not production ready  i must not use this.

I will do a custom pubsub for this.

Thanks for the answering on this.

On Monday, July 8, 2013, Jonathan James wrote:

> It has to do with how you map a foreign key (the _key_ property in
> mappings) to an _id. For example:
> 
> a._id <- b.foreignKey is reverse
> a.foreignKey -> b._id is not reverse
> 
> _Note: this package currently has some bugs that make it generally
> unusable in production. As an alternative, try storing the required data
> from one subscription in a reactive data type on the client side, such as a
> Session variable, and using Deps.autorun to re-run dependent subscriptions
> as that data changes._
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/erundook/meteor-publish-with-relations/issues/10#issuecomment-20580982
> .

## 

Arunoda Susiripala

@arunoda http://twitter.com/arunoda
http://gplus.to/arunodahttps://github.com/arunoda
http://www.linkedin.com/in/arunoda
