### ISSUE TITLE
Reactive relations?

### ISSUE THREAD

**Issue by dradovic** [svasva/meteor-publish-with-relations#8]
Hi,

Thanks for sharing this very useful package. I have one question though. Are the relations that are published along supposed to be reactive as well? In your example, are newly inserted comments pushed automatically to the client?

Cheers

**Comment by svasva** [comment]
Sure they are!

**Comment by dradovic** [comment]
Is it working with arrays as foreign keys as well? I have a 'Group' structure, holding user IDs in its 'memberIds' array. And I publish the users belonging to a group like this:

``` javascript
Meteor.publish("groups", function(userId) {
  return Meteor.publishWithRelations({
    handle: this,
    collection: Groups,
    filter: {
      $or: [
        {
          ownerId: userId
        }, {
          memberIds: userId
        }
      ]
    },
    mappings: [
      {
        key: "memberIds",
        collection: Meteor.users
      }
    ]
  });
});
```

It seems that updating the memberIds array is not pushing the changes to the client.

**Comment by svasva** [comment]
I didn't test it with arrays as foreign keys, so not sure if that should work.

**Comment by dradovic** [comment]
So, shall I open another issue having exactly this as a topic? Are you going to test it?
